firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "9100"
  - "3000"
  - "9090"

firewall_state: started
firewall_enabled_at_boot: true

prometheus_targets:
  node: # This is a base file name. File is located in "{{ prometheus_config_dir }}/file_sd/<<BASENAME>>.yml"
    - targets: #
        # - localhost:9100 # All this is a targets section in file_sd format
        - 192.168.2.2:9100
        - 192.168.2.3:9100
        - 192.168.2.4:9100
        - 192.168.2.5:9100
        - 192.168.2.6:9100
        - 192.168.2.7:9100
        - 192.168.2.8:9100
      labels: #
        env: lamp-stack #

grafana_security:
  admin_user: admin
  admin_password: 3rp@dm1n
