---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    # - name: Add ansible stable repository from PPA and install its signing key on Ubuntu target
    #   apt_repository:
    #     repo: ppa:ansible/ansible
      
    - name: Install a list of packages
      apt:
        pkg:
        - curl
        - software-properties-common
        - ansible
        - git
        - python3-pip
        - libssl-dev


  roles:
    - geerlingguy.php
    # - role: crivetimihai.virtualization.kvm
      #    - role: crivetimihai.virtualization.lxd
      #    - role: crivetimihai.virtualization.vmware_workstation
    - role: crivetimihai.virtualization.virtualbox
    #   #    - role: crivetimihai.virtualization.podman
    # - role: crivetimihai.virtualization.docker
    # - role: crivetimihai.virtualization.vagrant
    # - role: crivetimihai.virtualization.packer