
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.synced_folder "/vagrant", "/vagrant", disabled: true
  config.vm.define "sample1" do |sample1|
    sample1.vm.box = "sample1"
  end

end
