---
- hosts: localhost
  gather_facts: no

  vars_files:
    - creds.yml
    - vars.yml

  tasks:
    - name: Ensure boto3 is install locally
      pip:
        name: boto
        state: present

    - name: Create security group for webserver on AWS
      ec2_group:
        name: webserverSG
        description: Webserver security group that allows ssh and http
        region: us-east-2
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

    - name: launching ec2 instance for webserver
      ec2:
        key_name: jerome
        instance_type: t2.micro
        image: ami-0d9a6b6c74aafb9d7
        wait: true
        group: webserverSG
        count: 1
        vpc_subnet_id: subnet-29303853
        assign_public_ip: yes
        region: us-east-2
        state: present
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_tags:
          Name: webserver
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webserver
      loop: "{{ ec2.instances }}"

    - name: Wait for ssh to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        state: started
      loop: "{{ ec2.instances }}"

    - name: Running role
      include_role:
        name: geerlingguy.apache
