---
- hosts: lamp-varnish
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - sys_fs.varnish

  tasks:
    - name: Copy Varnish default.vcl.
      template:
        src: "templates/default.vcl.j2"
        dest: "/etc/varnish/default.vcl"
      notify: restart varnish