---
# Configure chef server
- name: Create initial user and organization
  block:
    - name: Setup chef config location
      file:
        path: "~/.chef/"
        state: directory     

    - name: Check Admin
      command: chef-server-ctl user-show {{ chefadmin_name }}
      ignore_errors: true
      register: check_user

    - name: Check Organization
      command: chef-server-ctl org-show {{ chef_organization }}
      ignore_errors: true
      register: check_org

    - name: Create Admin Credential
      command: |
        sudo chef-server-ctl user-create {{ chefadmin_name }} Chef Admin {{ chefadmin_email }}  {{ chefadmin_password }} \
        --filename ~/.chef/{{ chefadmin_name }}.pem
      become: yes
      when: check_user.rc !=0

    - name: Create Default organization
      command: |
        chef-server-ctl org-create {{ chef_organization }} {{ chef_organization_full_name }} \
        --association_user {{ chefadmin_name }} --filename ~/.chef/{{ chef_organization }}-validator.pem
      become: yes
      when: check_org.rc !=0
  when: create_default_credential | bool