---
- hosts: all
  become: yes
  
  vars_files:
    - vars.yml

  tasks:
# Set the hostname of and add entry to hosts file
    - name: Set hostname to chef-server if not defined
      hostname:
        name: chef-server
      when: chefserver_hostname is defined

    - name: Resolve hostname via /etc/hosts to resolve `hostname -f`
      lineinfile: 
        dest: /etc/hosts 
        line: "{{ansible_default_ipv4.address}} {{ansible_fqdn}} {{ansible_hostname}}"
      when: chefserver_hostname is defined

# Installation of necessary packages
    - name: Ensure required packages are installed
      apt:
        name:
          - ntp
          - unzip
          - vim
          - wget
          - curl
          - unzip
        state: present

    - name: Make sure ntp service is restarted
      service:
        name: ntp
        state: started

# Install Chef Server 
    - name: Check the chef-server package is installed
      ignore_errors: true
      command: which chef-server-ctl
      register: check_package

    - name: Check the management console installed
      ignore_errors: true
      uri:
        url: https://localhost/login
        validate_certs: false
      register: check_console

    - name: Install and Configure Chef Server
      block:
        - name: install the server
          apt:
            deb: "https://packages.chef.io/files/stable/chef-server/{{ chefserver_version }}/ubuntu/18.04/chef-server-core_{{ chefserver_version }}-1_amd64.deb"
            state: present
            update_cache: yes

        - name: Configure the server
          command: chef-server-ctl reconfigure
          become: yes
      when: check_package.rc != 0

    - name: Install management console
      block:
        - name: Install management component
          shell: |
            sudo chef-server-ctl install chef-manage
            yes

        - name: Reconfigure the server
          shell: sudo chef-server-ctl reconfigure

        - name: Reconfigure the manager
          shell: sudo chef-manage-ctl reconfigure --accept-license
      when: check_console.status != 200 and (install_management_console | bool)

# Configure chef server
    - name: Create initial user and organization
      block:
        - name: Setup chef config location
          file:
            path: ~/.chef/
            state: directory

        - name: Check Admin
          command: chef-server-ctl user-show {{ chefadmin_name }}
          ignore_errors: true
          register: check_user

        - name: Check Organization
          command: chef-server-ctl org-show {{ chef_organization }}
          ignore_errors: true
          register: check_org

        - name: Create Admin Credential
          command: |
            chef-server-ctl user-create {{ chefadmin_name }} Chef Admin {{ chefadmin_email }}  {{ chefadmin_password }} \
            --filename ~/.chef/{{ chefadmin_name }}.pem
          when: check_user.rc !=0

        - name: Create Default organization
          command: |
            chef-server-ctl org-create {{ chef_organization }} {{ chef_organization_full_name }} \
            --association_user {{ chefadmin_name }} --filename ~/.chef/{{ chef_organization }}-validator.pem
          when: check_org.rc !=0
      when: create_default_credential | bool