# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu1804"
  config.ssh.insert_key = false
  config.vm.synced_folder "src/", "/srv/website"
  
  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 8192
    v.cpus = 4
    v.linked_clone = true
  end

  # Chef server.
  config.vm.define "chefserver" do |chefserver|
    chefserver.vm.hostname = "chef-server.test"
    chefserver.vm.network :private_network, ip: "192.168.153.2"
  end
end
