---
- hosts: all
  become: true

  vars_files: 
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=true cache_valid_time=3600

  handlers:
    - name: restart solr
      service: name=solr state=restarted

  tasks:
    - name: Install Java.
      apt: name=openjdk-11-jdk state=present

    - name: Download Solr package with check (sha256)
      get_url:
        url: "https://downloads.apache.org/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        # checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  
    - name: Expand Solr
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: yes
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Run solr installation script
      command: >
        bash {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr

      
