# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |v|
    v.linked_clone = true
  end

  config.vm.define "solr" do |solr|
    solr.vm.box = "geerlingguy/ubuntu1804"
    solr.vm.hostname = "solr.test"
    solr.vm.network "private_network", ip: "192.168.56.121"
  end
  
end
