# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network :private_network, ip: "192.168.66.66"
  config.vm.hostname = "solr.lab"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Ansible provisioner.
  # config.vm.provision :ansible do |ansible|
  #   ansible.playbook = "provisioning/playbook.yml"
  # end
end
