---
firewall_allwed_tcp_port:
  - "22"
  - "3306"

mysql_replication_user: {name: 'replication', password: 'secret'}
mysql_databases:
  - name: mycompany_database
    collation: utf8_general_ci
    encoding: utf8