# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1804"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end

  config.vm.define "app1" do |app1|
    app1.vm.hostname = "jt-app1.test" 
    app1.vm.network :private_network, ip: "192.168.56.121"
  end

  config.vm.define "app2" do |app2|
    app2.vm.hostname = "jt-app2.test"
    app2.vm.network :private_network, ip: "192.168.56.122" 
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "jt-db.test" 
    db.vm.network :private_network, ip: "192.168.56.123"
  end

end
