# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "cdaf/WindowsServerCore"
  config.vm.box_version = "2.0.3"
  config.vm.network :private_network, ip: "192.168.2.2"
  config.vm.hostname = "win-host.lab"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 1200 # 20 minutes
  config.winrm.timeout = 1800 # 30 minutes
  config.winrm.max_tries = 20
  config.winrm.retry_limit = 200
  config.winrm.retry_delay = 10
  config.vm.graceful_halt_timeout = 600

  config.vm.provider :virtualbox do |v|
    v.memory = 8192
    v.cpus = 4
  end
end
