# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network :private_network, ip: "192.168.2.2"
  config.vm.hostname = "limesurvey.lab"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Ansible provisioner.
  # config.vm.provision :ansible do |ansible|
  #   ansible.playbook = "playbook.yml"
  # end

end