---
firewall_allowed_tcp_ports:
  - "22"
  - "80"

haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 80
haproxy_frontend_mode: 'http'

haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

haproxy_backend_servers:
  - name: web1
    address: 192.168.2.3:80
  - name: web2
    address: 192.168.2.4:80