---
- hosts: all
  become: true
  vars:
    drupal_core_version: "8.8.x"
    drupal_core_path: "/var/www/drupal-{{ drupal_core_version }}-dev"
    domain: "drupal"
    drupal_site_name: "Drupal Test"

  tasks:
    - name: Get software for apt repo management
      apt:
        name:
          - python-apt
          - python-pycurl
        state: present
    
    - name: Add ondrej repo for later PHP versions
      apt_repository:
        repo: 'ppa:ondrej/php'
        update_cache: yes

    - name: Install apache. mysql, php and depencies.
      apt:
        name:
          - git
          - curl
          - sendmail
          - apache2
          - php7.1-common
          - php7.1-cli
          - php7.1-dev
          - php7.1-gd
          - php7.1-curl
          - php7.1-json
          - php7.1-opcache
          - php7.1-xml
          - php7.1-mbstring
          - php7.1-pdo
          - php7.1-mysql
          - php-apcu
          - libpcre3-dev
          - libapache2-mod-php7.1
          - python-mysqldb
          - mysql-server
        state: present

    - name: Disable firewall (local dev)
      service: name=ufw state=stopped

    - name: Start apache, mysql and php services
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql

    - name: Enable apache rewrite module (required for drupal)
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: Add apache virtualhost for drupal 8 dev
      template:
        src: "templates/drupal.test.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: Symlink drupal virtualhost to sites-enabled.
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.test.conf"
        state: link
      notify: restart apache

    - name: Adjust OpCache memory setting
      lineinfile:
        dest: "/etc/php/7.1/apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
      notify: restart apache

    - name: Create a MySQL database for Drupal
      mysql_db: "db={{ domain }} state=present"
    
    - name: Create a MySql user for drupal
      mysql_user:
        name: "{{ domain }}"
        password: "1234"
        priv: "{{ domain }}.*:ALL"
        host: localhost
        state: present

    - name: Download composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Run composer installer
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move composer into globally-accessible location
      command: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    - name: Check out drush 8.x branch.
      git:
        repo: https://github.com/drush-ops/drush.git
        version: 8.x
        dest: /opt/drush

    - name: Install drush dependencies with composer
      command: >
        /usr/local/bin/composer install
        chdir=/opt/drush
        creates=/opt/drush/vendor/autoload.php

    - name: Create drush bin Symlink
      file:
        src: /opt/drush/drush
        dest: /usr/local/bin/drush
        state: link

    - name: Check out Drupal Core to the Apache docroot
      git:
        repo: https://git.drupal.org/project/drupal.git
        version: "{{ drupal_core_version }}"
        dest: "{{ drupal_core_path }}"
      register: git_checkout
      
    - name: Ensure Drupal codebase is owned by www-data
      file:
        path: "{{ drupal_core_path }}"
        owner: www-data
        group: www-data
        recurse: true
      when: git_checkout.changed | bool

    - name: Install Drupal dependencies with Composer
      command: >
        /usr/local/bin/composer install
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/vendor/autoload.php
      # become_user: www-data

    - name: Install Drupal
      command: >
        drush si -y --site-name="{{ drupal_site_name }}"
        --account-name=admin
        --account-pass=admin
        --db-url=mysql://{{ domain }}:1234@localhost/{{ domain }}\
        --root={{ drupal_core_path }}
        creates={{ drupal_core_path }}/sites/default/settings.php
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=apache state=restart