---
- name: Install and configure apache
  hosts: all
  become: true
  vars:
    node_app_location: /usr/local/opt/node
  
  tasks:
    - name: Install apache
      package:
        name:
          - apache2
        state: present

    - name: Allow apache on the firewall
      command: ufw allow 'Apache'

    - name: Start and enable apache2 service
      service: 
        name: apache2
        state: started
        enabled: yes

    
    
  #  - name: Copy configuration files
  #     copy:
  #       src: "{{ item.src }}"
  #       dest: "{{ item.dest }}"
  #       owner: root
  #       group: root
  #       mode: 0644
  #     with_items:
  #       - src: httpd.conf
  #         dest: /etc/httpd/conf/httpd.conf
  #       - src: httpd-vhosts.conf
  #         dest: /etc/httpd/conf/httpd-vhosts.conf
  #   - name: Make sure apache is started at boot and running
  #     service: name=httpd state=stated enabled=yes
      
