# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu1804"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "web1" do |web|
    web.vm.hostname = "jt-web.test"
    web.vm.network :private_network, ip: "192.168.56.121"
  end


end
