---
- hosts: all
  become: yes

  tasks:
    - name: Create group named lamp-www
      group:
<<<<<<< Updated upstream
        name: "lamp-www"
=======
        name: "lamp-www"

  roles:
    - cloudalchemy.node_exporter

>>>>>>> Stashed changes
