<<<<<<< HEAD
---
- hosts: lamp-web
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached

  tasks:
    - name: Remove the Apache test page.
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy my server-specific home page.
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php
=======
---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
  
>>>>>>> 93c80267e76f428f009fb9a29c79501336876609
